### ISSUE TITLE
饼状图数据title太长导致截取下移

### ISSUE THREAD

**Issue by wangdan3024** [WsmDyj/echarts-for-taro#11]
在使用饼状图的时候 因为数据title太长导致页面容纳不下，然后文字会截取成两部分 一部分在原本应该的位置显示，另外一部分显示到了下面，通过样式控制canvas超出隐藏不起作用，希望可以得到解决办法，非常感谢

**Comment by misszoessmile** [comment]
> 在使用饼状图的时候 因为数据title太长导致页面容纳不下，然后文字会截取成两部分 一部分在原本应该的位置显示，另外一部分显示到了下面，通过样式控制canvas超出隐藏不起作用，希望可以得到解决办法，非常感谢

请问你，有没有遇到过echarts编译失败的报错？
报错如下：
![image](https://user-images.githubusercontent.com/35720631/59339937-aefc5180-8d37-11e9-88d6-12afbf0888b4.png)

错误  编译失败  src\report\components\ec-canvas\echarts.js
{ TypeError: unknown: Property id of VariableDeclarator expected node to be of a type ["LVal"] but instead got "NumericLiteral"
    at Object.validate (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-types\lib\definitions\index.js:109:19)
    at Object.validate (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-types\lib\index.js:505:9)
    at NodePath._replaceWith (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\replacement.js:176:7)
    at NodePath.replaceWith (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\replacement.js:160:8)
    at replaceAndEvaluateNode (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-plugin-transform-define\lib\index.js:117:12)
    at processNode (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-plugin-transform-define\lib\index.js:143:5)
    at PluginPass.Identifier (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-plugin-transform-define\lib\index.js:23:9)
    at newFn (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:48:17) _babel: true }

**Comment by wangdan3024** [comment]
> > 在使用饼状图的时候 因为数据title太长导致页面容纳不下，然后文字会截取成两部分 一部分在原本应该的位置显示，另外一部分显示到了下面，通过样式控制canvas超出隐藏不起作用，希望可以得到解决办法，非常感谢
> 
> 请问你，有没有遇到过echarts编译失败的报错？
> 报错如下：
> ![image](https://user-images.githubusercontent.com/35720631/59339937-aefc5180-8d37-11e9-88d6-12afbf0888b4.png)
> 
> 错误 编译失败 src\report\components\ec-canvas\echarts.js
> { TypeError: unknown: Property id of VariableDeclarator expected node to be of a type ["LVal"] but instead got "NumericLiteral"
> at Object.validate (C:\Users\Administrator\AppData\Roaming\npm\node_modules@tarojs\cli\node_modules\babel-types\lib\definitions\index.js:109:19)
> at Object.validate (C:\Users\Administrator\AppData\Roaming\npm\node_modules@tarojs\cli\node_modules\babel-types\lib\index.js:505:9)
> at NodePath._replaceWith (C:\Users\Administrator\AppData\Roaming\npm\node_modules@tarojs\cli\node_modules\babel-traverse\lib\path\replacement.js:176:7)
> at NodePath.replaceWith (C:\Users\Administrator\AppData\Roaming\npm\node_modules@tarojs\cli\node_modules\babel-traverse\lib\path\replacement.js:160:8)
> at replaceAndEvaluateNode (C:\Users\Administrator\AppData\Roaming\npm\node_modules@tarojs\cli\node_modules\babel-plugin-transform-define\lib\index.js:117:12)
> at processNode (C:\Users\Administrator\AppData\Roaming\npm\node_modules@tarojs\cli\node_modules\babel-plugin-transform-define\lib\index.js:143:5)
> at PluginPass.Identifier (C:\Users\Administrator\AppData\Roaming\npm\node_modules@tarojs\cli\node_modules\babel-plugin-transform-define\lib\index.js:23:9)
> at newFn (C:\Users\Administrator\AppData\Roaming\npm\node_modules@tarojs\cli\node_modules\babel-traverse\lib\visitors.js:276:21)
> at NodePath._call (C:\Users\Administrator\AppData\Roaming\npm\node_modules@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:76:18)
> at NodePath.call (C:\Users\Administrator\AppData\Roaming\npm\node_modules@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:48:17) _babel: true }

没有遇上过，只遇上过编译成功了，但是小程序里面显示失败，一般重新编译就可以了
