### ISSUE TITLE
替换echarts.js报错

### ISSUE THREAD

**Issue by melody8yuen** [WsmDyj/echarts-for-taro#8]
我在echarts定制的echarts.min.js 替换项目中的echarts.js文件，小程序的图表出现报错，有什么解决办法吗？
![image](https://user-images.githubusercontent.com/7910920/56872703-a1785a00-6a5e-11e9-8df5-418583604ff2.png)

**Comment by wuyanghou** [comment]
请问解决了么

**Comment by wuyanghou** [comment]
@melody8yuen

**Comment by misszoessmile** [comment]
> 我在echarts定制的echarts.min.js 替换项目中的echarts.js文件，小程序的图表出现报错，有什么解决办法吗？
> ![image](https://user-images.githubusercontent.com/7910920/56872703-a1785a00-6a5e-11e9-8df5-418583604ff2.png)

请问你，有没有遇到过‘echarts编译失败’的报错？
报错信息如下：
![image](https://user-images.githubusercontent.com/35720631/59340053-d8b57880-8d37-11e9-8a10-ab307a799513.png)
错误  编译失败  src\report\components\ec-canvas\echarts.js
{ TypeError: unknown: Property id of VariableDeclarator expected node to be of a type ["LVal"] but instead got "NumericLiteral"
    at Object.validate (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-types\lib\definitions\index.js:109:19)
    at Object.validate (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-types\lib\index.js:505:9)
    at NodePath._replaceWith (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\replacement.js:176:7)
    at NodePath.replaceWith (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\replacement.js:160:8)
    at replaceAndEvaluateNode (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-plugin-transform-define\lib\index.js:117:12)
    at processNode (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-plugin-transform-define\lib\index.js:143:5)
    at PluginPass.Identifier (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-plugin-transform-define\lib\index.js:23:9)
    at newFn (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Users\Administrator\AppData\Roaming\npm\node_modules\@tarojs\cli\node_modules\babel-traverse\lib\path\context.js:48:17) _babel: true }

盼复，谢谢！

**Comment by JohnDarkKnight** [comment]
各位是如何减包的？总是报错啊

**Comment by JohnDarkKnight** [comment]
在线构建全量替换都会报错

**Comment by ellico** [comment]
我也遇到了这个问题，请问解决了吗？

**Comment by persist-xyz** [comment]
+1
